/* ==========================================================================
   Variation E -- "Glassmorphic Aurora"
   Curated book catalogue (a distinct subset of the shared Open Library data).
   Genres: Science Fiction, Fantasy, Science, Psychology, Young Adult, Thriller
   52 titles. Plain global (no modules -- must run from file://).
   ========================================================================== */

const BOOKS = [
  {
    id: "ol-OL17897265W",
    title: "A Closed and Common Orbit",
    subtitle: "",
    author: "Becky Chambers",
    year: 2016,
    genre: "Science Fiction",
    rating: 4.2,
    pages: 416,
    publisher: "Hodder & Stoughton",
    language: "English",
    isbn: "1515966429",
    cover: "assets/covers/ol-OL17897265W.jpg",
    coverFrom: "#200b65",
    coverTo: "#120637",
    tags: ["fiction in english", "science fiction", "fiction"],
    blurb: ["Once, Lovelace had eyes and ears everywhere. She was a ship's artificial intelligence system - possessing a personality and very human emotions. But when her ship was badly damaged, Lovelace was forced to reboot and reset. Now housed in an illegal synthetic body, she's never felt so isolated.", "But Lovelace is not alone. Pepper, an engineer who risked her life to reinstall Lovelace's program, has remained by her side and is determined to help her."],
    quote: null
  },
  {
    id: "ol-OL17062642W",
    title: "Ancillary Sword",
    subtitle: "",
    author: "Ann Leckie",
    year: 2014,
    genre: "Science Fiction",
    rating: 3.9,
    pages: 416,
    publisher: "J'ai lu",
    language: "English",
    isbn: "1478987375",
    cover: "assets/covers/ol-OL17062642W.jpg",
    coverFrom: "#0d2163",
    coverTo: "#071236",
    tags: ["science fiction", "fiction", "quests (expeditions)", "revenge"],
    blurb: ["Breq is a soldier who used to be a warship. Once a weapon of conquest controlling thousands of minds, now she has only a single body and serves the emperor.", "With a new ship and a troublesome crew, Breq is ordered to go to the only place in the galaxy she would agree to go: to Athoek Station to protect the family of a lieutenant she once knew - a lieutenant she murdered in cold blood."],
    quote: { text: "“Considering the circumstances, you could use another lieutenant.”", source: "First sentence" }
  },
  {
    id: "ol-OL17610507W",
    title: "Death's End (The Three-Body Problem Series Book 3)",
    subtitle: "",
    author: "刘慈欣",
    year: 2010,
    genre: "Science Fiction",
    rating: 4.4,
    pages: 724,
    publisher: "Whole Story Audiobooks",
    language: "English",
    isbn: "3453317661",
    cover: "assets/covers/ol-OL17610507W.jpg",
    coverFrom: "#59172c",
    coverTo: "#300d18",
    tags: ["fiction", "science fiction", "human-alien encounters", "survival"],
    blurb: ["“The War of the Worlds for the 21st century… packed with a sense of wonder.” – Wall Street Journal", "The New York Times bestselling conclusion to a tour de force near-future adventure trilogy from China's bestselling and beloved science fiction writer."],
    quote: { text: "Eigentlich sollte es *Geschichte* heißen, doch da die Verfasserin sich ausschließlich auf ihr Gedächtnis verlassen muss, mangelt es diesen Aufzeichnungen an historischer Genauigkeit.", source: "First sentence" }
  },
  {
    id: "ol-OL21775531W",
    title: "Destroy Me",
    subtitle: "",
    author: "Tahereh Mafi",
    year: 2012,
    genre: "Science Fiction",
    rating: 4.1,
    pages: 111,
    publisher: "Farshore",
    language: "English",
    isbn: "9789020632729",
    cover: "assets/covers/ol-OL21775531W.jpg",
    coverFrom: "#195850",
    coverTo: "#0d302c",
    tags: ["dystopian", "science fiction", "young adult", "romance"],
    blurb: ["In Shatter Me, Juliette escaped from The Reestablishment by seducing Warner -- and then putting a bullet in his shoulder. But as she'll learn in Destroy Me, Warner is not that easy to get rid of . . .", "Back at the base and recovering from his near-fatal wound, Warner must do everything in his power to keep his soldiers in check and suppress any mention of a rebellion in the sector. Still as obsessed with Juliette as ever, his first priority is to find her, bring her back, and dispose of Adam and Kenji, the two traitors who helped her escape. But when Warner's father, the Supreme Commander of The Reestablishment, arrives to correct his son's mistakes, it's clear that he has much different plans for Juliette. Plans Warner simply cannot allow"],
    quote: null
  },
  {
    id: "ol-OL17755458W",
    title: "Nemesis Games",
    subtitle: "",
    author: "James S. A. Corey",
    year: 2015,
    genre: "Science Fiction",
    rating: 4.2,
    pages: 536,
    publisher: "Orbit",
    language: "Italian",
    isbn: "0356504255",
    cover: "assets/covers/ol-OL17755458W.jpg",
    coverFrom: "#6a070d",
    coverTo: "#3a0407",
    tags: ["space warfare", "conspiracies", "interplanetary voyages", "fiction"],
    blurb: ["Nemesis Games is a science fiction work by James S. A. Corey, first published in 2015. The edition catalogued here runs to 536 pages. It was published by Orbit.", "Open Library catalogues it under space warfare, conspiracies and interplanetary voyages. Readers there give it an average rating of 4.2 out of 5. This record describes the Italian edition."],
    quote: null
  },
  {
    id: "ol-OL474061W",
    title: "Pandora's Star",
    subtitle: "",
    author: "Peter F. Hamilton",
    year: 2004,
    genre: "Science Fiction",
    rating: 4.1,
    pages: 896,
    publisher: "Random House Publishing Group",
    language: "German",
    isbn: "1405000198",
    cover: "assets/covers/ol-OL474061W.jpg",
    coverFrom: "#495818",
    coverTo: "#28300d",
    tags: ["fiction", "interplanetary voyages", "science fiction", "space colonies"],
    blurb: ["Critics have compared the engrossing space operas of Peter F. Hamilton to the classic sagas of such sf giants as Isaac Asimov and Frank Herbert. But Hamilton's bestselling fiction--powered by a fearless imagination and world-class storytelling skills--has also earned him comparison to Tolstoy and Dickens. Hugely ambitious, wildly entertaining, philosophically stimulating: the novels of Peter F. Hamilton will change the way you think about science fiction. Now, with Pandora's Star, he begins a new multivolume adventure, one that promises to be his most mind-blowing yet. The year is 2380."],
    quote: { text: "Mars completely dominated space outside Ulysses, the bloated dirty-ginger crescent of a planet that never quite made it as a world.", source: "First sentence" }
  },
  {
    id: "ol-OL16314245W",
    title: "The Dark Forest (The Three-Body Problem Series Book 2)",
    subtitle: "",
    author: "刘慈欣",
    year: 2008,
    genre: "Science Fiction",
    rating: 4.5,
    pages: 574,
    publisher: "Actes Sud",
    language: "English",
    isbn: "9861206884",
    cover: "assets/covers/ol-OL16314245W.jpg",
    coverFrom: "#31610f",
    coverTo: "#1b3508",
    tags: ["fiction", "science fiction", "human-alien encounters", "general"],
    blurb: ["\"Wildly imaginative.\" —President Barack Obama on The Three-Body Problem trilogy", "This near-future trilogy is the first chance for English-speaking readers to experience this multiple-award-winning phenomenon from Cixin Liu, China's most beloved science fiction author."],
    quote: { text: "Die braune Ameise hatte schon vergessen, dass sie hier einmal zu Hause gewesen war.", source: "First sentence" }
  },
  {
    id: "ol-OL5734646W",
    title: "The Last Colony",
    subtitle: "",
    author: "John Scalzi",
    year: 2007,
    genre: "Science Fiction",
    rating: 3.7,
    pages: 320,
    publisher: "Tor Books",
    language: "English",
    isbn: "8576574470",
    cover: "assets/covers/ol-OL5734646W.jpg",
    coverFrom: "#585518",
    coverTo: "#302f0d",
    tags: ["space warfare", "life on other planets", "fiction", "science fiction"],
    blurb: ["Serving his human colony on distant Huckleberry as a village ombudsman, retired fighter John Perry looks forward to settling into farm life with his wife and adopted daughter before he is drawn back into the dangerous interstellar politics of his past."],
    quote: null
  },
  {
    id: "ol-OL17716925W",
    title: "The Long Way to a Small, Angry Planet",
    subtitle: "",
    author: "Becky Chambers",
    year: 2014,
    genre: "Science Fiction",
    rating: 4.1,
    pages: 445,
    publisher: "HarperCollins B and Blackstone Publishing",
    language: "French",
    isbn: "9787555027706",
    cover: "assets/covers/ol-OL17716925W.jpg",
    coverFrom: "#1b1957",
    coverTo: "#0f0e30",
    tags: ["fiction", "science fiction", "interplanetary voyages", "space warfare"],
    blurb: ["When Rosemary Harper joins the crew of the Wayfarer, she isn't expecting much. The Wayfarer, a patched-up ship that's seen better days, offers her everything she could possibly want: a small, quiet spot to call home for a while, adventure in far-off corners of the galaxy, and distance from her troubled past.", "But Rosemary gets more than she bargained for with the Wayfarer. The crew is a mishmash of species and personalities, from Sissix, the friendly reptilian pilot, to Kizzy and Jenks, the constantly sparring engineers who keep the ship running. Life on board is chaotic, but more or less peaceful - exactly what Rosemary wants."],
    quote: { text: "Als sie in der Kapsel die Augen aufschlug, erinnerte sie sich an dreierlei.", source: "First sentence" }
  },
  {
    id: "ol-OL21703979W",
    title: "A Court of Silver Flames",
    subtitle: "",
    author: "Sarah J. Maas",
    year: 2021,
    genre: "Fantasy",
    rating: 4.4,
    pages: 768,
    publisher: "Crossbooks",
    language: "English",
    isbn: "1526633469",
    cover: "assets/covers/ol-OL21703979W.jpg",
    coverFrom: "#106051",
    coverTo: "#09342c",
    tags: ["fiction", "women spies", "fairies", "magic"],
    blurb: ["Sarah J. Maas's sexy, richly imagined Court of Thorns and Roses series continues with the journey of Feyre's fiery sister, Nesta.", "Nesta Archeron has always been prickly – proud, swift to anger and slow to forgive. And since the war – since being made High Fae against her will – she's struggled to forget the horrors she endured and find a place for herself within the strange and deadly Night Court."],
    quote: { text: "Cassian raised his fist to the green door in the dim hallway—and hesitated.", source: "First sentence" }
  },
  {
    id: "ol-OL17770504W",
    title: "Arcanum Unbounded",
    subtitle: "The Cosmere Collection",
    author: "Brandon Sanderson",
    year: 2016,
    genre: "Fantasy",
    rating: 4.6,
    pages: 672,
    publisher: "Tor Fantasy",
    language: "English",
    isbn: "0765395649",
    cover: "assets/covers/ol-OL17770504W.jpg",
    coverFrom: "#5b3516",
    coverTo: "#311d0c",
    tags: ["fiction", "fantasy fiction", "fantasy"],
    blurb: ["The first story collection by New York Times bestselling author Brandon Sanderson", "Brandon Sanderson creates worlds, and those worlds are linked. His universe spans the Stormlight Archive, the Mistborn series, the tales of Elantris, and others, comprising a unique constellation of vividly imagined realms known as the Cosmere."],
    quote: null
  },
  {
    id: "ol-OL26443093W",
    title: "Babel",
    subtitle: "Or the Necessity of Violence",
    author: "R. F. Kuang",
    year: 2022,
    genre: "Fantasy",
    rating: 4.2,
    pages: 569,
    publisher: "Hidra",
    language: "English",
    isbn: "9780008660567",
    cover: "assets/covers/ol-OL26443093W.jpg",
    coverFrom: "#5a1632",
    coverTo: "#310c1c",
    tags: ["translators", "fiction", "chinese", "imperialism"],
    blurb: ["From award-winning author R. F. Kuang comes Babel, a thematic response to The Secret History and a tonal retort to Jonathan Strange & Mr. Norrell that grapples with student revolutions, colonial resistance, and the use of language and translation as the dominating tool of the British empire.", "Traduttore, traditore: An act of translation is always an act of betrayal."],
    quote: { text: "By the time Professor Richard Lovell found his way through Canton’s narrow alleys to the faded address in his diary, the boy was the only one in the house left alive.", source: "First sentence" }
  },
  {
    id: "ol-OL8400949W",
    title: "Best served cold",
    subtitle: "",
    author: "Joe Abercrombie",
    year: 2009,
    genre: "Fantasy",
    rating: 4.3,
    pages: 632,
    publisher: "Orion Publishing Group, Limited",
    language: "French",
    isbn: "9788420683324",
    cover: "assets/covers/ol-OL8400949W.jpg",
    coverFrom: "#5c141d",
    coverTo: "#320b10",
    tags: ["fantasy", "fiction", "revenge"],
    blurb: ["War may be hell, but for Monza Murcatto, a solider of considerable fortune; it's a damn good way of making money too.  Her victories have made her popular - a shade too popular for her employer's taste. Betrayed and left for dead, Murcatto's reward is a broken body and a burning hunger for vengeance. Whatever the cost, seven men must die.", "Duke Orso imagines that he can become king by ending the civil wars that have devastated Styria, but he errs by trying to kill his overly popular general, mercenary Monza Murcatto. Recovering from her massive injuries and mourning her murdered brother, Monza vows vengeance on Orso and half a dozen of his accomplices."],
    quote: null
  },
  {
    id: "ol-OL5738147W",
    title: "Elantris",
    subtitle: "",
    author: "Brandon Sanderson",
    year: 2005,
    genre: "Fantasy",
    rating: 4.2,
    pages: 638,
    publisher: "Tor Fantasy",
    language: "English",
    isbn: "9788580445046",
    cover: "assets/covers/ol-OL5738147W.jpg",
    coverFrom: "#681508",
    coverTo: "#390b04",
    tags: ["princes", "blessing and cursing", "fiction", "princesses"],
    blurb: ["Elantris: gigantic, beautiful, radiant"],
    quote: { text: "Elantris was beautiful, once.", source: "First sentence" }
  },
  {
    id: "ol-OL17710016W",
    title: "Exile",
    subtitle: "",
    author: "Shannon Messenger",
    year: 2012,
    genre: "Fantasy",
    rating: 4.7,
    pages: 572,
    publisher: "Bound to Stay Bound Books",
    language: "English",
    isbn: "2371020273",
    cover: "assets/covers/ol-OL17710016W.jpg",
    coverFrom: "#19582e",
    coverTo: "#0d3019",
    tags: ["fantasy", "psychic ability", "ability", "memory"],
    blurb: ["Sophie is settling in nicely to her new home and her new life in the world of the lost cities. And it helps that living at Havenfield means getting to spend time with rare, precious species—including the first female Alicorn, who shows herself to Sophie and trusts no one but her.", "Sophie is tasked with helping to train the magical creature so that the Alicorn can be revealed to the people of the lost cities as a sign of hope, and Sophie wants to believe that the recent drama and anguish is gone for good."],
    quote: null
  },
  {
    id: "ol-OL5714289W",
    title: "Fire and Ice",
    subtitle: "",
    author: "Erin Hunter",
    year: 2003,
    genre: "Fantasy",
    rating: 4.3,
    pages: 344,
    publisher: "Perfection Learning Corporation",
    language: "English",
    isbn: "0061543004",
    cover: "assets/covers/ol-OL5714289W.jpg",
    coverFrom: "#660a20",
    coverTo: "#380611",
    tags: ["cats", "fantasy", "fantasy fiction", "feral cats"],
    blurb: ["Fireheart is a ThunderClan warrior cat now, but danger still lurks in the forest - and possibly closer than he thinks. With the chill of winter setting in, the cats of rival RiverClan are growing restless, while WindClan turns weak and faces threats from all sides.", "As tensions build up to an explosive climax, Fireheart faces not only imminent battle, but betrayal from within his own Clan."],
    quote: { text: "Orange flames lapped at the cold air, throwing sparks up into the night sky.", source: "First sentence" }
  },
  {
    id: "ol-OL17367560W",
    title: "Heir of Fire",
    subtitle: "",
    author: "Sarah J. Maas",
    year: 2014,
    genre: "Fantasy",
    rating: 4.2,
    pages: 584,
    publisher: "Turtleback",
    language: "English",
    isbn: "9789571061535",
    cover: "assets/covers/ol-OL17367560W.jpg",
    coverFrom: "#3b6110",
    coverTo: "#203509",
    tags: ["magic", "ya", "high fantasy", "fiction"],
    blurb: ["Celaena has survived deadly contests and shattering heartbreak-but at an unspeakable cost. Now, she must travel to a new land to confront her darkest truth…a truth about her heritage that could change her life-and her future-forever. Meanwhile, brutal and monstrous forces are gathering on the horizon, intent on enslaving her world. Will Celaena find the strength to not only fight her inner demons, but to take on the evil that is about to be unleashed?"],
    quote: null
  },
  {
    id: "ol-OL34028551W",
    title: "Iron Flame",
    subtitle: "",
    author: "Rebecca Yarros",
    year: 2023,
    genre: "Fantasy",
    rating: 4.3,
    pages: 640,
    publisher: "Entangled: Red Tower Books",
    language: "French",
    isbn: "0349437025",
    cover: "assets/covers/ol-OL34028551W.jpg",
    coverFrom: "#5b5715",
    coverTo: "#32300c",
    tags: ["fiction", "serie:the_empyrean", "fantasy"],
    blurb: ["“The first year is when some of us lose our lives. The second year is when the rest of us lose our humanity.” —Xaden Riorson", "Everyone expected Violet Sorrengail to die during her first year at Basgiath War College—Violet included. But Threshing was only the first impossible test meant to weed out the weak-willed, the unworthy, and the unlucky."],
    quote: { text: "Der Geschmack der Revolution ist überraschend ... süß.", source: "First sentence" }
  },
  {
    id: "ol-OL1892618W",
    title: "A Briefer History of Time",
    subtitle: "",
    author: "Stephen Hawking",
    year: 2005,
    genre: "Science",
    rating: 3.7,
    pages: 176,
    publisher: "Bantam Dell Pub Group",
    language: "Russian",
    isbn: "8377852969",
    cover: "assets/covers/ol-OL1892618W.jpg",
    coverFrom: "#5f0b65",
    coverTo: "#340637",
    tags: ["cosmology", "science / cosmology", "science", "nonfiction"],
    blurb: ["The science classic made more accessible and more concise. Illustrated. Updated with new research.Stephen Hawking's worldwide bestseller, A Brief History of Time, has been a landmark volume in scientific writing. Its author's engaging voice is one reason, and the compelling subjects he addresses is another: the nature of space and time, the role of God in creation, the history and future of the universe."],
    quote: null
  },
  {
    id: "ol-OL2698159W",
    title: "An introduction to the physics of nuclei and particles",
    subtitle: "",
    author: "R. A. Dunlap",
    year: 2003,
    genre: "Science",
    rating: null,
    pages: 284,
    publisher: "Thomson/Brooks-Cole",
    language: "English",
    isbn: "0534392946",
    cover: "assets/covers/ol-OL2698159W.jpg",
    coverFrom: "#620e4c",
    coverTo: "#350829",
    tags: ["nuclear physics", "physics", "science"],
    blurb: ["An introduction to the physics of nuclei and particles is a science work by R. A. Dunlap, first published in 2003. The edition catalogued here runs to 284 pages. It was published by Thomson/Brooks-Cole.", "Open Library catalogues it under nuclear physics, physics and science. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL12176120W",
    title: "College physics",
    subtitle: "a strategic approach",
    author: "Randall Dewey Knight",
    year: 2006,
    genre: "Science",
    rating: null,
    pages: 1088,
    publisher: "Pearson Publishing",
    language: "English",
    isbn: "0321879724",
    cover: "assets/covers/ol-OL12176120W.jpg",
    coverFrom: "#0d6448",
    coverTo: "#073627",
    tags: ["textbooks", "physics", "science / physics", "science - physics"],
    blurb: ["College physics is a science work by Randall Dewey Knight, first published in 2006. The edition catalogued here runs to 1088 pages. It was published by Pearson Publishing.", "Open Library catalogues it under textbooks, physics and science / physics. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL21015217W",
    title: "International Review of Cell and Molecular Biology",
    subtitle: "",
    author: "Kwang W. Jeon",
    year: 2008,
    genre: "Science",
    rating: null,
    pages: 342,
    publisher: "Elsevier Science & Technology",
    language: "English",
    isbn: "9780124076945",
    cover: "assets/covers/ol-OL21015217W.jpg",
    coverFrom: "#14495c",
    coverTo: "#0b2832",
    tags: ["molecular biology", "cytology", "cells", "science"],
    blurb: ["International Review of Cell and Molecular Biology is a science work by Kwang W. Jeon, first published in 2008. The edition catalogued here runs to 342 pages. It was published by Elsevier Science & Technology.", "Open Library catalogues it under molecular biology, cytology and cells. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL17419991W",
    title: "Jordan St Claire Dark And Dangerous",
    subtitle: "",
    author: "Carole Mortimer",
    year: 2011,
    genre: "Science",
    rating: 4.2,
    pages: 188,
    publisher: "Mills Boon",
    language: "English",
    isbn: "0263219305",
    cover: "assets/covers/ol-OL17419991W.jpg",
    coverFrom: "#11525f",
    coverTo: "#092d34",
    tags: ["fiction", "actors", "physical therapists"],
    blurb: ["Physiotherapist Stephanie has a new job, which turns out to be a request from a millionaire to help his younger brother, who is unable to walk. She never could have guessed that the millionaire is one of her favorite actors—he’s Jordan Simpson! After an accident on the job, he shut himself away behind his dark eyes and in his mansion. Stephanie fights her attraction to him—those thoughts are unprofessional and she must hide them. But that task suddenly becomes a lot harder once Jordan steals a kiss from her!"],
    quote: null
  },
  {
    id: "ol-OL18715742W",
    title: "Mcknight's physical geography",
    subtitle: "",
    author: "Darrel Hess",
    year: 2010,
    genre: "Science",
    rating: null,
    pages: 672,
    publisher: "Brand: Pearson",
    language: "English",
    isbn: "013426309X",
    cover: "assets/covers/ol-OL18715742W.jpg",
    coverFrom: "#591720",
    coverTo: "#310c11",
    tags: ["physical geography", "physics", "science"],
    blurb: ["Mcknight's physical geography is a science work by Darrel Hess, first published in 2010. The edition catalogued here runs to 672 pages. It was published by Brand: Pearson.", "Open Library catalogues it under physical geography, physics and science. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL24602178W",
    title: "Quantum physics for beginners",
    subtitle: "",
    author: "Carl J Pratt",
    year: 2021,
    genre: "Science",
    rating: null,
    pages: 84,
    publisher: "Stefano Solimito",
    language: "English",
    isbn: "1802356584",
    cover: "assets/covers/ol-OL24602178W.jpg",
    coverFrom: "#125e42",
    coverTo: "#0a3424",
    tags: ["physics", "science"],
    blurb: ["Quantum physics for beginners is a science work by Carl J Pratt, first published in 2021. The edition catalogued here runs to 84 pages. It was published by Stefano Solimito.", "Open Library catalogues it under physics and science. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL21445456W",
    title: "University Physics with Modern Physics",
    subtitle: "",
    author: "Hugh D. Young",
    year: 2007,
    genre: "Science",
    rating: null,
    pages: 1008,
    publisher: "Pearson Education, Limited",
    language: "English",
    isbn: "9781292100340",
    cover: "assets/covers/ol-OL21445456W.jpg",
    coverFrom: "#086847",
    coverTo: "#043926",
    tags: ["physics", "science"],
    blurb: ["University Physics with Modern Physics is a science work by Hugh D. Young, first published in 2007. The edition catalogued here runs to 1008 pages. It was published by Pearson Education, Limited.", "Open Library catalogues it under physics and science. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL25742643W",
    title: "A Macat Analysis of Daniel Kahneman's Thinking, Fast and Slow",
    subtitle: "",
    author: "Jacqueline Allan",
    year: 2018,
    genre: "Psychology",
    rating: 4,
    pages: null,
    publisher: "Taylor & Francis Group",
    language: "English",
    isbn: "1912453053",
    cover: "assets/covers/ol-OL25742643W.jpg",
    coverFrom: "#5e3d12",
    coverTo: "#33210a",
    tags: ["psychology"],
    blurb: ["A Macat Analysis of Daniel Kahneman's Thinking, Fast and Slow is a psychology work by Jacqueline Allan, first published in 2018. It was published by Taylor & Francis Group.", "Open Library catalogues it under psychology. Readers there give it an average rating of 4.0 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL17930368W",
    title: "Atomic Habits",
    subtitle: "",
    author: "James Clear",
    year: 2016,
    genre: "Psychology",
    rating: 4,
    pages: 322,
    publisher: "Avery, an Imprint of Penguin Random House LLC",
    language: "French",
    isbn: "6052998385",
    cover: "assets/covers/ol-OL17930368W.jpg",
    coverFrom: "#066a56",
    coverTo: "#033a2f",
    tags: ["habit", "habit breaking", "behavior modification", "business"],
    blurb: ["No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. Atomic Habits pdf"],
    quote: null
  },
  {
    id: "ol-OL16929630W",
    title: "Attached",
    subtitle: "",
    author: "Amir Levine",
    year: 2010,
    genre: "Psychology",
    rating: 4.2,
    pages: 294,
    publisher: "Tarcher",
    language: "English",
    isbn: "1585428485",
    cover: "assets/covers/ol-OL16929630W.jpg",
    coverFrom: "#175919",
    coverTo: "#0d310e",
    tags: ["attachment behavior", "intimacy (psychology)", "psychology"],
    blurb: ["Introduces the theory of adult attachment as an advanced relationship science that can enable individuals to find and sustain love, offering insight into the roles of genetics and early family life in how people approach relationships."],
    quote: null
  },
  {
    id: "ol-OL16215950W",
    title: "Breaking the habit of being yourself",
    subtitle: "",
    author: "Joe Dispenza",
    year: 2012,
    genre: "Psychology",
    rating: 3.9,
    pages: 352,
    publisher: "Ediciones Urano",
    language: "English",
    isbn: "1848508565",
    cover: "assets/covers/ol-OL16215950W.jpg",
    coverFrom: "#5f3f11",
    coverTo: "#342209",
    tags: ["new thought", "thought and thinking", "change (psychology)", "thinking"],
    blurb: ["Argues that all human beings have the power within them to overcome predisposed beliefs and habits to make significant changes in one's life, and provides step-by-step tools to make such changes using understandings between science and spirituality."],
    quote: null
  },
  {
    id: "ol-OL29743214W",
    title: "Dream Psychology",
    subtitle: "",
    author: "Sigmund Freud",
    year: 2017,
    genre: "Psychology",
    rating: 4.3,
    pages: 255,
    publisher: "Independently published",
    language: "English",
    isbn: "9781090530066",
    cover: "assets/covers/ol-OL29743214W.jpg",
    coverFrom: "#541060",
    coverTo: "#2e0934",
    tags: ["psychology", "psychoanalysis", "dreams", "dream interpretation"],
    blurb: ["The Interpretation of Dreams is a book by Sigmund Freud. The first edition was first published in German in November 1899 as Die Traumdeutung (though post-dated as 1900 by the publisher). The publication inaugurated the theory of Freudian dream analysis, which activity Freud famously described as \"the royal road to the understanding of unconscious mental processes\"."],
    quote: null
  },
  {
    id: "ol-OL2392324W",
    title: "Eat That Frog! 21 Great Ways to Stop Procrastinating and Get More Done in Less Time",
    subtitle: "",
    author: "Brian Tracy",
    year: 2001,
    genre: "Psychology",
    rating: 3.9,
    pages: 128,
    publisher: "Audio Literature",
    language: "English",
    isbn: "162656941X",
    cover: "assets/covers/ol-OL2392324W.jpg",
    coverFrom: "#365c15",
    coverTo: "#1d320b",
    tags: ["procrastination", "dilación", "time management", "berrett koehler"],
    blurb: ["There just isn't enough time for everything on our to-do list—and there never will be. Successful people don't try to do everything. They learn to focus on the most important tasks and make sure those get done. They eat their frogs.", "There's an old saying that if the first thing you do each morning is eat a live frog, you'll have the satisfaction of knowing you're done with the worst thing you'll have to do all day. For Tracy, eating a frog is a metaphor for tackling your most challenging task—but also the one that can have the greatest positive impact on your life. Eat That Frog! — Snapshots shows you how to organize each day so you can zero in on these critical tasks and accomplish them efficiently and effectively."],
    quote: { text: "\"BEFORE YOU CAN determine your \"\"frog\"\" and get on with eating it, you have to decide exactly what you want to accomplish in each area of your life.\"", source: "First sentence" }
  },
  {
    id: "ol-OL20033244W",
    title: "Ego is the Enemy",
    subtitle: "",
    author: "Ryan Holiday",
    year: 2016,
    genre: "Psychology",
    rating: 3.8,
    pages: 238,
    publisher: "Ediciones Culturales Paidós",
    language: "German",
    isbn: "1781257027",
    cover: "assets/covers/ol-OL20033244W.jpg",
    coverFrom: "#115f23",
    coverTo: "#093413",
    tags: ["conduct of life", "egoism", "success", "ambition"],
    blurb: ["Many of us insist the main impediment to a full, successful life is the outside world. In fact, the most common enemy lies within: our ego. Early in our careers, it impedes learning and the cultivation of talent. With success, it can blind us to our faults and sow future problems. In failure, it magnifies each blow and makes recovery more difficult. At every stage, ego holds us back. Ego Is the Enemy draws on a vast array of stories and examples, from literature to philosophy to history."],
    quote: null
  },
  {
    id: "ol-OL20884418W",
    title: "Good Vibes, Good Life",
    subtitle: "",
    author: "Vex King",
    year: 2015,
    genre: "Psychology",
    rating: 3.3,
    pages: 304,
    publisher: "Hay House UK, Limited",
    language: "English",
    isbn: "9386832836",
    cover: "assets/covers/ol-OL20884418W.jpg",
    coverFrom: "#604410",
    coverTo: "#352509",
    tags: ["self-acceptance", "psychology"],
    blurb: ["Good Vibes, Good Life is a psychology work by Vex King, first published in 2015. The edition catalogued here runs to 304 pages. It was published by Hay House UK, Limited.", "Open Library catalogues it under self-acceptance and psychology. Readers there give it an average rating of 3.3 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL20464319W",
    title: "Indistractable",
    subtitle: "How to Control Your Attention and Choose Your Life",
    author: "Nir Eyal",
    year: 2019,
    genre: "Psychology",
    rating: 3.9,
    pages: 336,
    publisher: "Benbella Books",
    language: "English",
    isbn: "9781526625335",
    cover: "assets/covers/ol-OL20464319W.jpg",
    coverFrom: "#0d6316",
    coverTo: "#07360c",
    tags: ["psychology", "goal (psychology)", "technology", "attention"],
    blurb: ["You sit down at your desk to work on an important project, but a notification on your phone interrupts your morning. Later, as you're about to get back to work, a colleague taps you on the shoulder to chat. At home, screens get in the way of quality time with your family. Another day goes by, and once again, your most important personal and professional goals are put on hold. What would be possible if you followed through on your best intentions? What could you accomplish if you could stay focused and overcome distractions? What if you had the power to become \"indistractable\"?"],
    quote: null
  },
  {
    id: "ol-OL17370186W",
    title: "A Little Life",
    subtitle: "",
    author: "Hanya Yanagihara",
    year: 2008,
    genre: "Young Adult",
    rating: 4,
    pages: 800,
    publisher: "Doğan Kitap",
    language: "English",
    isbn: "9781447294825",
    cover: "assets/covers/ol-OL17370186W.jpg",
    coverFrom: "#591724",
    coverTo: "#300d14",
    tags: ["lgbtq novels", "coming of age", "literary", "sagas"],
    blurb: ["A Little Life is a 2015 novel by American novelist Hanya Yanagihara. The novel was written over the course of eighteen months. Despite the length and difficult subject matter, it became a bestseller. A Little Life pdf"],
    quote: null
  },
  {
    id: "ol-OL20035152W",
    title: "All the ugly and wonderful things",
    subtitle: "",
    author: "Bryn Greenwood",
    year: 2016,
    genre: "Young Adult",
    rating: null,
    pages: 392,
    publisher: "Audible Studios on Brilliance",
    language: "English",
    isbn: "9781466885806",
    cover: "assets/covers/ol-OL20035152W.jpg",
    coverFrom: "#105260",
    coverTo: "#092d35",
    tags: ["motorcyclists", "dysfunctional families", "bildungsromans", "children"],
    blurb: ["\"As the daughter of a drug dealer, Wavy knows not to trust people, not even her own parents. It's safer to keep her mouth shut and stay out of sight. Struggling to raise her little brother, Donal, eight-year-old Wavy is the only responsible adult around. Obsessed with the constellations, she finds peace in the starry night sky above the fields behind her house, until one night her star gazing causes an accident. After witnessing his motorcycle wreck, she forms an unusual friendship with one of her father's thugs, Kellen, a tattooed ex-con with a heart of gold."],
    quote: null
  },
  {
    id: "ol-OL92967W",
    title: "Angus, Thongs and Full-Frontal Snogging",
    subtitle: "Confessions of Georgia Nicolson",
    author: "Louise Rennison",
    year: 2000,
    genre: "Young Adult",
    rating: 3.5,
    pages: 247,
    publisher: "Perfection Learning Prebound",
    language: "English",
    isbn: "0439998301",
    cover: "assets/covers/ol-OL92967W.jpg",
    coverFrom: "#5d131e",
    coverTo: "#330a10",
    tags: ["humorous stories", "teenage girls", "diaries", "juvenile fiction"],
    blurb: ["Presents the humorous journal of a year in the life of a fourteen-year-old British girl who tries to reduce the size of her nose, stop her mad cat from terrorizing the neighborhood animals, and win the love of handsome hunk Robbie."],
    quote: { text: "\"Dad had Uncle Eddie round, so naturally they had to come and see what I was up to.\"", source: "First sentence" }
  },
  {
    id: "ol-OL24156366W",
    title: "Boys don't cry",
    subtitle: "",
    author: "Malorie Blackman",
    year: 2010,
    genre: "Young Adult",
    rating: null,
    pages: 296,
    publisher: "Galaxy Plus",
    language: "English",
    isbn: "1445820013",
    cover: "assets/covers/ol-OL24156366W.jpg",
    coverFrom: "#22670a",
    coverTo: "#133805",
    tags: ["teenage fathers", "fiction", "single parents"],
    blurb: ["Boys don't cry is a young adult work by Malorie Blackman, first published in 2010. The edition catalogued here runs to 296 pages. It was published by Galaxy Plus.", "Open Library catalogues it under teenage fathers, fiction and single parents. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL1763376W",
    title: "Bringing Tony home",
    subtitle: "",
    author: "Tissa Abēsēkara",
    year: 2008,
    genre: "Young Adult",
    rating: null,
    pages: 224,
    publisher: "Scala House Press",
    language: "English",
    isbn: "9781556437571",
    cover: "assets/covers/ol-OL1763376W.jpg",
    coverFrom: "#2d5918",
    coverTo: "#19300d",
    tags: ["fiction", "sri lanka", "coming of age"],
    blurb: ["\"Part memoir and part fiction, this collection of stories provides a historically compelling portrait of a young boy's childhood and coming of age in Sri Lanka in the 1940's and 1950's\"--Provided by publisher."],
    quote: null
  },
  {
    id: "ol-OL42975424W",
    title: "Can We Be Strangers Again?",
    subtitle: "",
    author: "Shrijeet Shandilya",
    year: 2024,
    genre: "Young Adult",
    rating: 3.6,
    pages: 232,
    publisher: "Notion Press Media Pvt. Limited",
    language: "English",
    isbn: "0143475924",
    cover: "assets/covers/ol-OL42975424W.jpg",
    coverFrom: "#0f5761",
    coverTo: "#083035",
    tags: ["young adult fiction", "young adult"],
    blurb: ["In the electric haze of college life, three friends are bound by laughter, late-night talks and unspoken promises. But when two of them cross the line from friendship into love, everything changes. Betrayal shatters their world, leaving one friend to pick up the pieces while navigating her own complicated feelings. As friendships fracture and love grows tangled, hearts are broken, and choices become irreversible. Caught between the ache of lost friendship and the bittersweet pull of love, Dev must decide if he’s willing to risk everything—again."],
    quote: null
  },
  {
    id: "ol-OL14910414W",
    title: "Chicken Soup Teenage Trilogy",
    subtitle: "",
    author: "Mark Victor Hansen",
    year: 2000,
    genre: "Young Adult",
    rating: null,
    pages: 30,
    publisher: "Health Communications",
    language: "English",
    isbn: "1558749993",
    cover: "assets/covers/ol-OL14910414W.jpg",
    coverFrom: "#4e640c",
    coverTo: "#2b3706",
    tags: ["conduct of life", "teenagers", "teenage"],
    blurb: ["Chicken Soup Teenage Trilogy is a young adult work by Mark Victor Hansen, first published in 2000. The edition catalogued here runs to 30 pages. It was published by Health Communications.", "Open Library catalogues it under conduct of life, teenagers and teenage. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL20875338W",
    title: "Culpa Tuya",
    subtitle: "",
    author: "Mercedes Ron",
    year: 2016,
    genre: "Young Adult",
    rating: 4,
    pages: 448,
    publisher: "Watped",
    language: "English",
    isbn: "8413142024",
    cover: "assets/covers/ol-OL20875338W.jpg",
    coverFrom: "#595017",
    coverTo: "#312c0d",
    tags: ["young adult"],
    blurb: ["Seventeen-year-old Noah Morgan loves her quiet, normal life in Toronto. But when her mother returns from a cruise unexpectedly married to a billionaire and announces they are moving to L.A., Noah is suddenly shoved out of her comfort zone and into a glittering world of illegal street races, lavish pool parties, and spoiled rich kids.", "And her new stepbrother Nicholas is the most spoiled of them all. Arrogant, aloof, and viciously attractive, Nick is everything she hates, especially when she learns his bad boy persona isn't just a façade. She's spent her life running from danger, and Nick is danger incarnate. Yet neither of them can prevent the powerful attraction that flares between them—enough to turn their worlds upside-down and tempt them beyond all reason."],
    quote: null
  },
  {
    id: "ol-OL27052926W",
    title: "Demon Copperhead",
    subtitle: "",
    author: "Barbara Kingsolver",
    year: 2022,
    genre: "Young Adult",
    rating: 5,
    pages: 560,
    publisher: "Faber & Faber, Limited",
    language: "English",
    isbn: "0571376479",
    cover: "assets/covers/ol-OL27052926W.jpg",
    coverFrom: "#61660a",
    coverTo: "#353706",
    tags: ["fiction", "coming of age", "literary fiction", "literature"],
    blurb: ["\"Anyone will tell you the born of this world are marked from the get-out, win or lose.\"", "Set in the mountains of southern Appalachia, this is the story of a boy born to a teenaged single mother in a single-wide trailer, with no assets beyond his dead father's good looks and copper-colored hair, a caustic wit, and a fierce talent for survival. In a plot that never pauses for breath, relayed in his own unsparing voice, he braves the modern perils of foster care, child labor, derelict schools, athletic success, addiction, disastrous loves, and crushing losses."],
    quote: null
  },
  {
    id: "ol-OL17864836W",
    title: "Cadáver exquisito",
    subtitle: "",
    author: "Agustina Bazterrica",
    year: 2015,
    genre: "Thriller",
    rating: 3.8,
    pages: 224,
    publisher: "clarin/alfaguara",
    language: "English",
    isbn: "9788366718357",
    cover: "assets/covers/ol-OL17864836W.jpg",
    coverFrom: "#225d13",
    coverTo: "#13330b",
    tags: ["romance literature", "fiction", "dystopias", "dystopies"],
    blurb: ["Working at the local processing plant, Marcos is in the business of slaughtering humans—though no one calls them that anymore.", "His wife has left him, his father is sinking into dementia, and Marcos tries not to think too hard about how he makes a living. After all, it happened so quickly. First, it was reported that an infectious virus has made all animal meat poisonous to humans. Then governments initiated the “Transition.” Now, eating human meat—“special meat”—is legal. Marcos tries to stick to numbers, consignments, processing."],
    quote: null
  },
  {
    id: "ol-OL29195444W",
    title: "Corrupted Chaos",
    subtitle: "",
    author: "Shain Rose",
    year: 2022,
    genre: "Thriller",
    rating: 3.8,
    pages: 372,
    publisher: "Meredith Wild LLC",
    language: "English",
    isbn: "9781956810073",
    cover: "assets/covers/ol-OL29195444W.jpg",
    coverFrom: "#28650b",
    coverTo: "#163706",
    tags: ["fiction", "thriller"],
    blurb: ["My enemy doesn’t make the rules… Even if he’s my boss.", "Cade Armanelli might be an infamous hacker with billionaire status who operates better alone, but I earned my spot working alongside him... Whether he likes it or not."],
    quote: null
  },
  {
    id: "ol-OL17781620W",
    title: "El día que se perdió la cordura",
    subtitle: "",
    author: "Javier Castillo",
    year: 2014,
    genre: "Thriller",
    rating: null,
    pages: 456,
    publisher: "SUMA",
    language: "Spanish",
    isbn: "8483659050",
    cover: "assets/covers/ol-OL17781620W.jpg",
    coverFrom: "#5e3d13",
    coverTo: "#33210a",
    tags: ["fiction", "united states", "thriller"],
    blurb: ["Amor, odio, destino, extrañas prácticas, intriga y acción trepidante inundan las páginas de la primera novela de Javier Castillo convertida en el fenómeno editorial del año. «A veces el destino nos pone a prueba para que sepamos que existe». Centro de Boston, 24 de diciembre, un hombre camina desnudo con la cabeza decapitada de una joven."],
    quote: null
  },
  {
    id: "ol-OL17333186W",
    title: "Finders Keepers",
    subtitle: "",
    author: "Stephen King",
    year: 2014,
    genre: "Thriller",
    rating: 4,
    pages: 448,
    publisher: "Simon & Schuster",
    language: "French",
    isbn: "9024567254",
    cover: "assets/covers/ol-OL17333186W.jpg",
    coverFrom: "#11155f",
    coverTo: "#090b34",
    tags: ["psychopaths", "authors", "recluses", "fans (persons)"],
    blurb: ["Overview: Wake up, genius. So announces deranged fan Morris Bellamy to iconic author John Rothstein, who once created the famous character Jimmy Gold and hasn't released anything since. Morris is livid, not just because his favorite writer has stopped publishing, but because Jimmy Gold ended up as a sellout. Morris kills his idol and empties his safe of cash, but the real haul is a collection of notebooks containing John Rothstein's unpublished work - including at least one more Jimmy Gold novel. Morris hides everything away before being locked up for another horrific crime."],
    quote: null
  },
  {
    id: "ol-OL81586W",
    title: "From a Buick 8",
    subtitle: "",
    author: "Stephen King",
    year: 2002,
    genre: "Thriller",
    rating: 3.8,
    pages: 463,
    publisher: "Paw Prints",
    language: "Russian",
    isbn: "9780340874592",
    cover: "assets/covers/ol-OL81586W.jpg",
    coverFrom: "#10601d",
    coverTo: "#093410",
    tags: ["ghost story", "drunk driving", "angel dust", "horror fiction"],
    blurb: ["Una novela sobre una fascinación enfermiza y peligrosa. Una novela de verdadero terror. Pensilvania, 1979. Llega un extraño a una gasolinera para repostar. Conduce un Buick modelo 1954 pero en perfecto estado. El conductor va al baño y nunca reaparece. La policía se hace cargo del coche, que ahora no funciona, y lo guarda en una nave detrás de la comisaría. Y aquí empieza una historia escalofriante, la historia de un coche con su propia vida, perversa y maliciosa. Los agentes siguen su trabajo, pero el coche de vez en cuando interviene: a veces sus radios y teléfonos no funcionan."],
    quote: null
  },
  {
    id: "ol-OL263241W",
    title: "From the Corner of His Eye",
    subtitle: "",
    author: "Dean Koontz",
    year: 2000,
    genre: "Thriller",
    rating: 3.6,
    pages: 729,
    publisher: "Brand: Random House Audio",
    language: "Spanish",
    isbn: "0747270716",
    cover: "assets/covers/ol-OL263241W.jpg",
    coverFrom: "#131b5d",
    coverTo: "#0a0f33",
    tags: ["teenage boys", "stalking victims", "vision", "fiction"],
    blurb: ["From the Corner of His Eye is a thriller work by Dean Koontz, first published in 2000. The edition catalogued here runs to 729 pages. It was published by Brand: Random House Audio.", "Open Library catalogues it under teenage boys, stalking victims and vision. Readers there give it an average rating of 3.6 out of 5. This record describes the Spanish edition."],
    quote: null
  },
  {
    id: "ol-OL278110W",
    title: "Heart-Shaped Box",
    subtitle: "",
    author: "Joe Hill",
    year: 2007,
    genre: "Thriller",
    rating: 3.4,
    pages: 404,
    publisher: "Harper Collins Publishers",
    language: "Spanish",
    isbn: "1415937559",
    cover: "assets/covers/ol-OL278110W.jpg",
    coverFrom: "#1a066b",
    coverTo: "#0e033a",
    tags: ["fiction", "horror fiction", "adult fiction", "thrillers"],
    blurb: ["Judas Coyne is a collector of the macabre: a cookbook for cannibals . . . a used hangman's noose . . . a snuff film. An aging death-metal rock god, his taste for the unnatural is as widely known to his legions of fans as the notorious excesses of his youth. But nothing he possesses is as unlikely or as dreadful as his latest discovery, an item for sale on the Internet, a thing so terribly strange, Jude can't help but reach for his wallet.I will \"sell\" my stepfather's ghost to the highest bidder. . ."],
    quote: null
  },
  {
    id: "ol-OL20537509W",
    title: "Hideaway",
    subtitle: "",
    author: "Penelope Douglas",
    year: 2017,
    genre: "Thriller",
    rating: 3.9,
    pages: 474,
    publisher: "CreateSpace Independent Publishing Platform",
    language: "English",
    isbn: "9781976333002",
    cover: "assets/covers/ol-OL20537509W.jpg",
    coverFrom: "#4c1061",
    coverTo: "#2a0835",
    tags: ["fiction", "american literature", "romance", "dark"],
    blurb: ["Buried in the shadows of the city, there’s a hotel called The Pope. Ailing, empty, and dark—it sits abandoned and surrounded by a forgotten mystery.", "But you think it’s true, don’t you, Kai Mori? The story about the hidden twelfth floor. The mystery of the dark guest who never checked in and never checks out. You think I can help you find that secret hideaway and get to him, don’t you?"],
    quote: null
  }
];
